//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Datos.EF
{
    using System;
    using System.Data.Entity;
     using TP3.Entidades.EF;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_CLINICA_RPEntities : DbContext
    {
        public BD_CLINICA_RPEntities()
            : base("name=BD_CLINICA_RPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_ACTA_EJEC_MANTENIMIENTO> T_ACTA_EJEC_MANTENIMIENTO { get; set; }
        public virtual DbSet<T_ACTA_EJEC_MANTENIMIENTO_DET> T_ACTA_EJEC_MANTENIMIENTO_DET { get; set; }
        public virtual DbSet<T_BIEN> T_BIEN { get; set; }
        public virtual DbSet<T_DETALLE_HISTORIA_CLINICA> T_DETALLE_HISTORIA_CLINICA { get; set; }
        public virtual DbSet<T_EMPLEADO> T_EMPLEADO { get; set; }
        public virtual DbSet<T_EMPRESA> T_EMPRESA { get; set; }
        public virtual DbSet<T_EQUIPO_MEDICO> T_EQUIPO_MEDICO { get; set; }
        public virtual DbSet<T_ESPECIALIDAD_MEDICA> T_ESPECIALIDAD_MEDICA { get; set; }
        public virtual DbSet<T_EVALUACION_SIGNOS_VITALES> T_EVALUACION_SIGNOS_VITALES { get; set; }
        public virtual DbSet<T_HISTORIA_CLINICA> T_HISTORIA_CLINICA { get; set; }
        public virtual DbSet<T_INMUEBLE> T_INMUEBLE { get; set; }
        public virtual DbSet<T_MANTENIMIENTO_EQUIPO> T_MANTENIMIENTO_EQUIPO { get; set; }
        public virtual DbSet<T_MODELO> T_MODELO { get; set; }
        public virtual DbSet<T_MUEBLE> T_MUEBLE { get; set; }
        public virtual DbSet<T_ORDEN_ATENCION> T_ORDEN_ATENCION { get; set; }
        public virtual DbSet<T_PACIENTE> T_PACIENTE { get; set; }
        public virtual DbSet<T_PERSONA> T_PERSONA { get; set; }
        public virtual DbSet<T_PLAN_MANTENIMIENTO> T_PLAN_MANTENIMIENTO { get; set; }
        public virtual DbSet<T_RESERVA_SERVICIO> T_RESERVA_SERVICIO { get; set; }
        public virtual DbSet<T_RESULTADO_ATENCION> T_RESULTADO_ATENCION { get; set; }
        public virtual DbSet<T_ROL> T_ROL { get; set; }
        public virtual DbSet<T_SERVICIO_SALUD> T_SERVICIO_SALUD { get; set; }
        public virtual DbSet<T_SOLICITUD_MANTENIMIENTO> T_SOLICITUD_MANTENIMIENTO { get; set; }
        public virtual DbSet<T_SOLICITUD_UCI> T_SOLICITUD_UCI { get; set; }
        public virtual DbSet<T_TAREA_MANTENIMIENTO> T_TAREA_MANTENIMIENTO { get; set; }
        public virtual DbSet<T_TECNICO_MANTENIMIENTO> T_TECNICO_MANTENIMIENTO { get; set; }
        public virtual DbSet<T_USUARIO> T_USUARIO { get; set; }
        public virtual DbSet<T_EQUIPO_USO> T_EQUIPO_USO { get; set; }
    
        public virtual int InsertarSolicitudUCI(Nullable<System.DateTime> fechaSolicitud, string estPaciente, string medSolicitante, string gravedad, string motDesaprobacion, string obsDesaprobacion, Nullable<int> idPaciente)
        {
            var fechaSolicitudParameter = fechaSolicitud.HasValue ?
                new ObjectParameter("fechaSolicitud", fechaSolicitud) :
                new ObjectParameter("fechaSolicitud", typeof(System.DateTime));
    
            var estPacienteParameter = estPaciente != null ?
                new ObjectParameter("estPaciente", estPaciente) :
                new ObjectParameter("estPaciente", typeof(string));
    
            var medSolicitanteParameter = medSolicitante != null ?
                new ObjectParameter("medSolicitante", medSolicitante) :
                new ObjectParameter("medSolicitante", typeof(string));
    
            var gravedadParameter = gravedad != null ?
                new ObjectParameter("gravedad", gravedad) :
                new ObjectParameter("gravedad", typeof(string));
    
            var motDesaprobacionParameter = motDesaprobacion != null ?
                new ObjectParameter("motDesaprobacion", motDesaprobacion) :
                new ObjectParameter("motDesaprobacion", typeof(string));
    
            var obsDesaprobacionParameter = obsDesaprobacion != null ?
                new ObjectParameter("obsDesaprobacion", obsDesaprobacion) :
                new ObjectParameter("obsDesaprobacion", typeof(string));
    
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("idPaciente", idPaciente) :
                new ObjectParameter("idPaciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarSolicitudUCI", fechaSolicitudParameter, estPacienteParameter, medSolicitanteParameter, gravedadParameter, motDesaprobacionParameter, obsDesaprobacionParameter, idPacienteParameter);
        }
    
        public virtual ObjectResult<T_PACIENTE> ListarPacientes(string estado)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_PACIENTE>("ListarPacientes", estadoParameter);
        }
    
        public virtual ObjectResult<T_PACIENTE> ListarPacientes(string estado, MergeOption mergeOption)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_PACIENTE>("ListarPacientes", mergeOption, estadoParameter);
        }
    
        public virtual ObjectResult<T_PACIENTE> obtenerPaciente(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_PACIENTE>("obtenerPaciente", idParameter);
        }
    
        public virtual ObjectResult<T_PACIENTE> obtenerPaciente(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_PACIENTE>("obtenerPaciente", mergeOption, idParameter);
        }
    
        public virtual int ActualizarPaciente(Nullable<int> idPaciente, string dniPaciente, Nullable<System.DateTime> fechNacimiento, string segmentacion, Nullable<int> codPersona, string estado)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("idPaciente", idPaciente) :
                new ObjectParameter("idPaciente", typeof(int));
    
            var dniPacienteParameter = dniPaciente != null ?
                new ObjectParameter("dniPaciente", dniPaciente) :
                new ObjectParameter("dniPaciente", typeof(string));
    
            var fechNacimientoParameter = fechNacimiento.HasValue ?
                new ObjectParameter("fechNacimiento", fechNacimiento) :
                new ObjectParameter("fechNacimiento", typeof(System.DateTime));
    
            var segmentacionParameter = segmentacion != null ?
                new ObjectParameter("segmentacion", segmentacion) :
                new ObjectParameter("segmentacion", typeof(string));
    
            var codPersonaParameter = codPersona.HasValue ?
                new ObjectParameter("codPersona", codPersona) :
                new ObjectParameter("codPersona", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPaciente", idPacienteParameter, dniPacienteParameter, fechNacimientoParameter, segmentacionParameter, codPersonaParameter, estadoParameter);
        }
    }
}
