//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ANTECEDENTES
    {
        public int idAntecedentes { get; set; }
        public string dscAntecedentes { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public int idHistoriaClinica { get; set; }
    
        public virtual T_HISTORIA_CLINICA T_HISTORIA_CLINICA { get; set; }
    }
}
