//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DETALLE_HISTORIA_CLINICA
    {
        public int idDetalleHC { get; set; }
        public int nroHistoriaClinica { get; set; }
        public string diagnóstico { get; set; }
        public Nullable<int> idEvaluacionSignosVitales { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idResultado { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<System.DateTime> fecRegistro { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_EVALUACION_SIGNOS_VITALES T_EVALUACION_SIGNOS_VITALES { get; set; }
        public virtual T_RESULTADO_ATENCION T_RESULTADO_ATENCION { get; set; }
        public virtual T_SOLICITUD_UCI T_SOLICITUD_UCI { get; set; }
        public virtual T_HISTORIA_CLINICA T_HISTORIA_CLINICA { get; set; }
    }
}
