//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EQUIPO_USO
    {
        public int idEquipoMedico { get; set; }
        public Nullable<System.DateTime> fecUso { get; set; }
    
        public virtual T_EQUIPO_MEDICO T_EQUIPO_MEDICO { get; set; }
    }
}
