//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESPECIALIDAD_MEDICA
    {
        public T_ESPECIALIDAD_MEDICA()
        {
            this.T_EMPLEADO = new HashSet<T_EMPLEADO>();
        }
    
        public int idEspecialidad { get; set; }
        public string nomEspecialidad { get; set; }
    
        public virtual ICollection<T_EMPLEADO> T_EMPLEADO { get; set; }
    }
}
