//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESPECIALIDAD_MEDICA
    {
        public T_ESPECIALIDAD_MEDICA()
        {
            this.T_EQUIPO_MEDICO = new HashSet<T_EQUIPO_MEDICO>();
            this.T_SERVICIO_SALUD = new HashSet<T_SERVICIO_SALUD>();
        }
    
        public int idEspecialidad { get; set; }
        public string nomEspecialidad { get; set; }
    
        public virtual ICollection<T_EQUIPO_MEDICO> T_EQUIPO_MEDICO { get; set; }
        public virtual ICollection<T_SERVICIO_SALUD> T_SERVICIO_SALUD { get; set; }
    }
}
