//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EVENTO_HISTORIA_CLINICA
    {
        public int idDetalleHC { get; set; }
        public Nullable<int> idResultado { get; set; }
        public Nullable<System.DateTime> fechaEjecucion { get; set; }
        public Nullable<int> idResultadoExamen { get; set; }
        public int idHistoriaClinica { get; set; }
        public string nroHistoriaClinica { get; set; }
        public int idPaciente { get; set; }
        public string tipoEvento { get; set; }
    
        public virtual T_RESULTADO_ATENCION T_RESULTADO_ATENCION { get; set; }
        public virtual T_RESULTADO_EXAMEN T_RESULTADO_EXAMEN { get; set; }
        public virtual T_HISTORIA_CLINICA T_HISTORIA_CLINICA { get; set; }
    }
}
