//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EVALUACION_SIGNOS_VITALES
    {
        public T_EVALUACION_SIGNOS_VITALES()
        {
            this.T_DETALLE_HISTORIA_CLINICA = new HashSet<T_DETALLE_HISTORIA_CLINICA>();
        }
    
        public int idEvaluacionSignosVitales { get; set; }
        public Nullable<int> pulso { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public Nullable<decimal> presionSistolica { get; set; }
        public Nullable<decimal> presionDiastolica { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual ICollection<T_DETALLE_HISTORIA_CLINICA> T_DETALLE_HISTORIA_CLINICA { get; set; }
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
    }
}
