//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXAMEN_TRATAMIENTO
    {
        public int idExamenTratamiento { get; set; }
        public int idTratamiento { get; set; }
        public int idResultadoExamen { get; set; }
    
        public virtual T_TRATAMIENTO_UCI T_TRATAMIENTO_UCI { get; set; }
        public virtual T_RESULTADO_EXAMEN T_RESULTADO_EXAMEN { get; set; }
    }
}
