//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HISTORIA_CLINICA
    {
        public T_HISTORIA_CLINICA()
        {
            this.T_ANTECEDENTES = new HashSet<T_ANTECEDENTES>();
            this.T_EVENTO_HISTORIA_CLINICA = new HashSet<T_EVENTO_HISTORIA_CLINICA>();
        }
    
        public int idHistoriaClinica { get; set; }
        public string nroHistoriaClinica { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string tipoEvento { get; set; }
        public int idPaciente { get; set; }
    
        public virtual ICollection<T_ANTECEDENTES> T_ANTECEDENTES { get; set; }
        public virtual ICollection<T_EVENTO_HISTORIA_CLINICA> T_EVENTO_HISTORIA_CLINICA { get; set; }
        public virtual T_PACIENTE T_PACIENTE { get; set; }
    }
}
