//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MANTENIMIENTO_EQUIPO
    {
        public T_MANTENIMIENTO_EQUIPO()
        {
            this.T_ACTA_EJEC_MANTENIMIENTO = new HashSet<T_ACTA_EJEC_MANTENIMIENTO>();
        }
    
        public int idMantEquipo { get; set; }
        public string codPlan { get; set; }
        public Nullable<System.DateTime> fecMantenimiento1 { get; set; }
        public Nullable<System.DateTime> fecMantenimiento2 { get; set; }
        public Nullable<System.DateTime> fecMantenimiento3 { get; set; }
        public string dscTipoMantenimiento { get; set; }
        public string estMantenimiento { get; set; }
        public Nullable<int> idEquipoMedico { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> codEmpresa { get; set; }
    
        public virtual ICollection<T_ACTA_EJEC_MANTENIMIENTO> T_ACTA_EJEC_MANTENIMIENTO { get; set; }
        public virtual T_EMPRESA T_EMPRESA { get; set; }
        public virtual T_EQUIPO_MEDICO T_EQUIPO_MEDICO { get; set; }
        public virtual T_PLAN_MANTENIMIENTO T_PLAN_MANTENIMIENTO { get; set; }
        public virtual T_SOLICITUD_MANTENIMIENTO T_SOLICITUD_MANTENIMIENTO { get; set; }
    }
}
