//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MODELO
    {
        public T_MODELO()
        {
            this.T_MUEBLE = new HashSet<T_MUEBLE>();
        }
    
        public int codModelo { get; set; }
        public string nomModelo { get; set; }
        public string dscMarca { get; set; }
    
        public virtual ICollection<T_MUEBLE> T_MUEBLE { get; set; }
    }
}
