//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MUEBLE
    {
        public int codMueble { get; set; }
        public string dscFuncion { get; set; }
        public string dscAplicacionMedica { get; set; }
        public Nullable<bool> garantia { get; set; }
        public string tipoMueble { get; set; }
        public Nullable<int> codBien { get; set; }
        public Nullable<int> codEmpresa { get; set; }
        public Nullable<int> codModelo { get; set; }
    
        public virtual T_BIEN T_BIEN { get; set; }
        public virtual T_EMPRESA T_EMPRESA { get; set; }
        public virtual T_MODELO T_MODELO { get; set; }
    }
}
