//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDEN_ATENCION
    {
        public T_ORDEN_ATENCION()
        {
            this.T_RESULTADO_ATENCION = new HashSet<T_RESULTADO_ATENCION>();
        }
    
        public int idAtencion { get; set; }
        public string tipoAtencion { get; set; }
        public string tipoCliente { get; set; }
        public Nullable<System.DateTime> fecAtencion { get; set; }
        public Nullable<System.DateTime> horInicio { get; set; }
        public Nullable<System.DateTime> horFin { get; set; }
        public string tipoEntregaResultado { get; set; }
        public string estado { get; set; }
        public Nullable<int> idReserva { get; set; }
    
        public virtual T_RESERVA_SERVICIO T_RESERVA_SERVICIO { get; set; }
        public virtual ICollection<T_RESULTADO_ATENCION> T_RESULTADO_ATENCION { get; set; }
    }
}
