//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PACIENTE
    {
        public T_PACIENTE()
        {
            this.T_HISTORIA_CLINICA = new HashSet<T_HISTORIA_CLINICA>();
            this.T_RESERVA_SERVICIO = new HashSet<T_RESERVA_SERVICIO>();
            this.T_SOLICITUD_UCI = new HashSet<T_SOLICITUD_UCI>();
        }
    
        public int idPaciente { get; set; }
        public string dniPaciente { get; set; }
        public Nullable<System.DateTime> fechNacimiento { get; set; }
        public string segmentacion { get; set; }
        public Nullable<int> codPersona { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<T_HISTORIA_CLINICA> T_HISTORIA_CLINICA { get; set; }
        public virtual T_PERSONA T_PERSONA { get; set; }
        public virtual ICollection<T_RESERVA_SERVICIO> T_RESERVA_SERVICIO { get; set; }
        public virtual ICollection<T_SOLICITUD_UCI> T_SOLICITUD_UCI { get; set; }
    }
}
