//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PLAN_MANTENIMIENTO
    {
        public T_PLAN_MANTENIMIENTO()
        {
            this.T_MANTENIMIENTO_EQUIPO = new HashSet<T_MANTENIMIENTO_EQUIPO>();
        }
    
        public string codPlan { get; set; }
        public Nullable<System.DateTime> fecRegistro { get; set; }
        public string estPlan { get; set; }
        public Nullable<int> idTecnicoMant { get; set; }
    
        public virtual ICollection<T_MANTENIMIENTO_EQUIPO> T_MANTENIMIENTO_EQUIPO { get; set; }
        public virtual T_TECNICO_MANTENIMIENTO T_TECNICO_MANTENIMIENTO { get; set; }
    }
}
