//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGISTRO_UCI
    {
        public T_REGISTRO_UCI()
        {
            this.T_SOLICITUD_UCI = new HashSet<T_SOLICITUD_UCI>();
        }
    
        public int idRegistro { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
    
        public virtual ICollection<T_SOLICITUD_UCI> T_SOLICITUD_UCI { get; set; }
    }
}
