//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RESULTADO_EXAMEN
    {
        public T_RESULTADO_EXAMEN()
        {
            this.T_EVALUACION_SIGNOS_VITALES = new HashSet<T_EVALUACION_SIGNOS_VITALES>();
            this.T_EVALUACION_TISS = new HashSet<T_EVALUACION_TISS>();
            this.T_EVENTO_HISTORIA_CLINICA = new HashSet<T_EVENTO_HISTORIA_CLINICA>();
            this.T_EXAMEN_TRATAMIENTO = new HashSet<T_EXAMEN_TRATAMIENTO>();
        }
    
        public int idResultadoExamen { get; set; }
        public Nullable<System.DateTime> fechaExamen { get; set; }
        public Nullable<System.DateTime> fechaResultado { get; set; }
        public string diagnostico { get; set; }
        public string tipoExamen { get; set; }
        public byte[] imagenResultado { get; set; }
        public Nullable<int> idResultado { get; set; }
        public Nullable<int> idTratamenito { get; set; }
        public Nullable<int> idRecomendacion { get; set; }
    
        public virtual ICollection<T_EVALUACION_SIGNOS_VITALES> T_EVALUACION_SIGNOS_VITALES { get; set; }
        public virtual ICollection<T_EVALUACION_TISS> T_EVALUACION_TISS { get; set; }
        public virtual ICollection<T_EVENTO_HISTORIA_CLINICA> T_EVENTO_HISTORIA_CLINICA { get; set; }
        public virtual ICollection<T_EXAMEN_TRATAMIENTO> T_EXAMEN_TRATAMIENTO { get; set; }
        public virtual T_RESULTADO_ATENCION T_RESULTADO_ATENCION { get; set; }
        public virtual T_TRATAMIENTO_UCI T_TRATAMIENTO_UCI { get; set; }
        public virtual T_RECOMENDACION_TRATAMIENTO T_RECOMENDACION_TRATAMIENTO { get; set; }
    }
}
