//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RESERVA_SERVICIO
    {
        public T_RESERVA_SERVICIO()
        {
            this.T_ORDEN_ATENCION = new HashSet<T_ORDEN_ATENCION>();
        }
    
        public int idReserva { get; set; }
        public Nullable<System.DateTime> fecReserva { get; set; }
        public string tipoAtencion { get; set; }
        public string tipoCliente { get; set; }
        public string estado { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idPaciente { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual ICollection<T_ORDEN_ATENCION> T_ORDEN_ATENCION { get; set; }
        public virtual T_PACIENTE T_PACIENTE { get; set; }
        public virtual T_SERVICIO_SALUD T_SERVICIO_SALUD { get; set; }
    }
}
