//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RESULTADO_ATENCION
    {
        public T_RESULTADO_ATENCION()
        {
            this.T_DETALLE_HISTORIA_CLINICA = new HashSet<T_DETALLE_HISTORIA_CLINICA>();
        }
    
        public int idResultado { get; set; }
        public string valorResultado { get; set; }
        public string diagnostico { get; set; }
        public Nullable<System.DateTime> conclusion { get; set; }
        public Nullable<System.DateTime> fecResultado { get; set; }
        public string estado { get; set; }
        public Nullable<int> idAtencion { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual ICollection<T_DETALLE_HISTORIA_CLINICA> T_DETALLE_HISTORIA_CLINICA { get; set; }
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_ORDEN_ATENCION T_ORDEN_ATENCION { get; set; }
    }
}
