//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ROL
    {
        public T_ROL()
        {
            this.T_USUARIO = new HashSet<T_USUARIO>();
        }
    
        public int idRol { get; set; }
        public string nombreRol { get; set; }
        public string tipoRol { get; set; }
        public string estRol { get; set; }
    
        public virtual ICollection<T_USUARIO> T_USUARIO { get; set; }
    }
}
