//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SERVICIO_SALUD
    {
        public T_SERVICIO_SALUD()
        {
            this.T_RESERVA_SERVICIO = new HashSet<T_RESERVA_SERVICIO>();
        }
    
        public int idServicio { get; set; }
        public string tipoServicio { get; set; }
        public string nomServicio { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
    
        public virtual ICollection<T_RESERVA_SERVICIO> T_RESERVA_SERVICIO { get; set; }
    }
}
