//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SOLICITUD_UCI
    {
        public T_SOLICITUD_UCI()
        {
            this.T_TRATAMIENTO_UCI = new HashSet<T_TRATAMIENTO_UCI>();
        }
    
        public int idSolicitud { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public string observacion { get; set; }
        public string estadoSolicitud { get; set; }
        public string gravedadPaciente { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public string numeroSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEvaluacion { get; set; }
        public string tipoTraslado { get; set; }
        public string dscMedicinaTraslado { get; set; }
        public string tipoEquipoMedico { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idResultado { get; set; }
        public Nullable<int> idRegistro { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_PACIENTE T_PACIENTE { get; set; }
        public virtual T_REGISTRO_UCI T_REGISTRO_UCI { get; set; }
        public virtual T_RESULTADO_ATENCION T_RESULTADO_ATENCION { get; set; }
        public virtual ICollection<T_TRATAMIENTO_UCI> T_TRATAMIENTO_UCI { get; set; }
    }
}
