//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SOLICITUD_UCI
    {
        public T_SOLICITUD_UCI()
        {
            this.T_DETALLE_HISTORIA_CLINICA = new HashSet<T_DETALLE_HISTORIA_CLINICA>();
        }
    
        public int idSolicitud { get; set; }
        public Nullable<System.DateTime> fechSolicitud { get; set; }
        public string estPaciente { get; set; }
        public string medSolicitante { get; set; }
        public string gravedad { get; set; }
        public string motDesaprobacion { get; set; }
        public string obsDesaprobacion { get; set; }
        public Nullable<int> idPaciente { get; set; }
    
        public virtual ICollection<T_DETALLE_HISTORIA_CLINICA> T_DETALLE_HISTORIA_CLINICA { get; set; }
        public virtual T_PACIENTE T_PACIENTE { get; set; }
    }
}
