//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TECNICO_MANTENIMIENTO
    {
        public T_TECNICO_MANTENIMIENTO()
        {
            this.T_PLAN_MANTENIMIENTO = new HashSet<T_PLAN_MANTENIMIENTO>();
            this.T_SOLICITUD_MANTENIMIENTO = new HashSet<T_SOLICITUD_MANTENIMIENTO>();
        }
    
        public int idTecnicoMant { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public string experienciaTrabajoRiesgo { get; set; }
        public string seguroRiesgo { get; set; }
        public Nullable<System.DateTime> vigenciaEPP { get; set; }
        public Nullable<System.DateTime> vigenciaExamenMedicoOcup { get; set; }
        public string habilidades { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual ICollection<T_PLAN_MANTENIMIENTO> T_PLAN_MANTENIMIENTO { get; set; }
        public virtual ICollection<T_SOLICITUD_MANTENIMIENTO> T_SOLICITUD_MANTENIMIENTO { get; set; }
    }
}
