//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRATAMIENTO_UCI
    {
        public T_TRATAMIENTO_UCI()
        {
            this.T_EXAMEN_TRATAMIENTO = new HashSet<T_EXAMEN_TRATAMIENTO>();
        }
    
        public int idTratamiento { get; set; }
        public Nullable<System.DateTime> fechaTratamiento { get; set; }
        public string resultado { get; set; }
        public string observacion { get; set; }
        public string medicinaTratamiento { get; set; }
        public string frecuencia { get; set; }
        public Nullable<int> idSolicitud { get; set; }
    
        public virtual ICollection<T_EXAMEN_TRATAMIENTO> T_EXAMEN_TRATAMIENTO { get; set; }
        public virtual T_SOLICITUD_UCI T_SOLICITUD_UCI { get; set; }
    }
}
