//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USUARIO
    {
        public T_USUARIO()
        {
            this.T_ROL = new HashSet<T_ROL>();
        }
    
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> codEmpresa { get; set; }
        public string EstUsuario { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_EMPRESA T_EMPRESA { get; set; }
        public virtual ICollection<T_ROL> T_ROL { get; set; }
    }
}
